# Generated by Django 4.2.2 on 2023-07-06 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friendships", "0002_rename_friendrequest_friend"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friend",
            old_name="receiver_id",
            new_name="receiver",
        ),
        migrations.RenameField(
            model_name="friend",
            old_name="sender_id",
            new_name="sender",
        ),
    ]
